set(__QT_DEPLOY_TARGET_GBAEmulator_FILE /Users/alexwaldmann/Desktop/AIO Server/lib/libGBAEmulator.a)
set(__QT_DEPLOY_TARGET_GBAEmulator_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_AIOServer_FILE /Users/alexwaldmann/Desktop/AIO Server/bin/AIOServer)
set(__QT_DEPLOY_TARGET_AIOServer_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_gtest_FILE /Users/alexwaldmann/Desktop/AIO Server/lib/libgtest.a)
set(__QT_DEPLOY_TARGET_gtest_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gtest_main_FILE /Users/alexwaldmann/Desktop/AIO Server/lib/libgtest_main.a)
set(__QT_DEPLOY_TARGET_gtest_main_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gmock_FILE /Users/alexwaldmann/Desktop/AIO Server/lib/libgmock.a)
set(__QT_DEPLOY_TARGET_gmock_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gmock_main_FILE /Users/alexwaldmann/Desktop/AIO Server/lib/libgmock_main.a)
set(__QT_DEPLOY_TARGET_gmock_main_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_CPUTests_FILE /Users/alexwaldmann/Desktop/AIO Server/bin/CPUTests)
set(__QT_DEPLOY_TARGET_CPUTests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_HeadlessTest_FILE /Users/alexwaldmann/Desktop/AIO Server/bin/HeadlessTest)
set(__QT_DEPLOY_TARGET_HeadlessTest_TYPE EXECUTABLE)
